<?php

namespace Database\Seeders;

use App\Models\Pais;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $countries = [
      ['idPais' => 1, 'nombrePais' => 'Afghanistan'],
      ['idPais' => 2, 'nombrePais' => 'Albania'],
      ['idPais' => 3, 'nombrePais' => 'Algeria'],
      ['idPais' => 4, 'nombrePais' => 'American Samoa'],
      ['idPais' => 5, 'nombrePais' => 'Andorra'],
      ['idPais' => 6, 'nombrePais' => 'Angola'],
      ['idPais' => 7, 'nombrePais' => 'Anguilla'],
      ['idPais' => 8, 'nombrePais' => 'Antarctica'],
      ['idPais' => 9, 'nombrePais' => 'Antigua And Barbuda'],
      ['idPais' => 10, 'nombrePais' => 'Argentina'],
      ['idPais' => 11, 'nombrePais' => 'Armenia'],
      ['idPais' => 12, 'nombrePais' => 'Aruba'],
      ['idPais' => 13, 'nombrePais' => 'Australia'],
      ['idPais' => 14, 'nombrePais' => 'Austria'],
      ['idPais' => 15, 'nombrePais' => 'Azerbaijan'],
      ['idPais' => 16, 'nombrePais' => 'Bahamas The'],
      ['idPais' => 17, 'nombrePais' => 'Bahrain'],
      ['idPais' => 18, 'nombrePais' => 'Bangladesh'],
      ['idPais' => 19, 'nombrePais' => 'Barbados'],
      ['idPais' => 20, 'nombrePais' => 'Belarus'],
      ['idPais' => 21, 'nombrePais' => 'Belgium'],
      ['idPais' => 22, 'nombrePais' => 'Belize'],
      ['idPais' => 23, 'nombrePais' => 'Benin'],
      ['idPais' => 24, 'nombrePais' => 'Bermuda'],
      ['idPais' => 25, 'nombrePais' => 'Bhutan'],
      ['idPais' => 26, 'nombrePais' => 'Bolivia'],
      ['idPais' => 27, 'nombrePais' => 'Bosnia and Herzegovina'],
      ['idPais' => 28, 'nombrePais' => 'Botswana'],
      ['idPais' => 29, 'nombrePais' => 'Bouvet Island'],
      ['idPais' => 30, 'nombrePais' => 'Brazil'],
      ['idPais' => 31, 'nombrePais' => 'British Indian Ocean Territory'],
      ['idPais' => 32, 'nombrePais' => 'Brunei'],
      ['idPais' => 33, 'nombrePais' => 'Bulgaria'],
      ['idPais' => 34, 'nombrePais' => 'Burkina Faso'],
      ['idPais' => 35, 'nombrePais' => 'Burundi'],
      ['idPais' => 36, 'nombrePais' => 'Cambodia'],
      ['idPais' => 37, 'nombrePais' => 'Cameroon'],
      ['idPais' => 38, 'nombrePais' => 'Canada'],
      ['idPais' => 39, 'nombrePais' => 'Cape Verde'],
      ['idPais' => 40, 'nombrePais' => 'Cayman Islands'],
      ['idPais' => 41, 'nombrePais' => 'Central African Republic'],
      ['idPais' => 42, 'nombrePais' => 'Chad'],
      ['idPais' => 43, 'nombrePais' => 'Chile'],
      ['idPais' => 44, 'nombrePais' => 'China'],
      ['idPais' => 45, 'nombrePais' => 'Christmas Island'],
      ['idPais' => 46, 'nombrePais' => 'Cocos (Keeling) Islands'],
      ['idPais' => 47, 'nombrePais' => 'Colombia'],
      ['idPais' => 48, 'nombrePais' => 'Comoros'],
      ['idPais' => 49, 'nombrePais' => 'Republic Of The Congo'],
      ['idPais' => 50, 'nombrePais' => 'Democratic Republic Of The Con'],
      ['idPais' => 51, 'nombrePais' => 'Cook Islands'],
      ['idPais' => 52, 'nombrePais' => 'Costa Rica'],
      ['idPais' => 53, 'nombrePais' => 'Cote DIvoire (Ivory Coast)'],
      ['idPais' => 54, 'nombrePais' => 'Croatia (Hrvatska)'],
      ['idPais' => 55, 'nombrePais' => 'Cuba'],
      ['idPais' => 56, 'nombrePais' => 'Cyprus'],
      ['idPais' => 57, 'nombrePais' => 'Czech Republic'],
      ['idPais' => 58, 'nombrePais' => 'Denmark'],
      ['idPais' => 59, 'nombrePais' => 'Djibouti'],
      ['idPais' => 60, 'nombrePais' => 'Dominica'],
      ['idPais' => 61, 'nombrePais' => 'Dominican Republic'],
      ['idPais' => 62, 'nombrePais' => 'East Timor'],
      ['idPais' => 63, 'nombrePais' => 'Ecuador'],
      ['idPais' => 64, 'nombrePais' => 'Egypt'],
      ['idPais' => 65, 'nombrePais' => 'El Salvador'],
      ['idPais' => 66, 'nombrePais' => 'Equatorial Guinea'],
      ['idPais' => 67, 'nombrePais' => 'Eritrea'],
      ['idPais' => 68, 'nombrePais' => 'Estonia'],
      ['idPais' => 69, 'nombrePais' => 'Ethiopia'],
      ['idPais' => 70, 'nombrePais' => 'External Territories of Austra'],
      ['idPais' => 71, 'nombrePais' => 'Falkland Islands'],
      ['idPais' => 72, 'nombrePais' => 'Faroe Islands'],
      ['idPais' => 73, 'nombrePais' => 'Fiji Islands'],
      ['idPais' => 74, 'nombrePais' => 'Finland'],
      ['idPais' => 75, 'nombrePais' => 'France'],
      ['idPais' => 76, 'nombrePais' => 'French Guiana'],
      ['idPais' => 77, 'nombrePais' => 'French Polynesia'],
      ['idPais' => 78, 'nombrePais' => 'French Southern Territories'],
      ['idPais' => 79, 'nombrePais' => 'Gabon'],
      ['idPais' => 80, 'nombrePais' => 'Gambia The'],
      ['idPais' => 81, 'nombrePais' => 'Georgia'],
      ['idPais' => 82, 'nombrePais' => 'Germany'],
      ['idPais' => 83, 'nombrePais' => 'Ghana'],
      ['idPais' => 84, 'nombrePais' => 'Gibraltar'],
      ['idPais' => 85, 'nombrePais' => 'Greece'],
      ['idPais' => 86, 'nombrePais' => 'Greenland'],
      ['idPais' => 87, 'nombrePais' => 'Grenada'],
      ['idPais' => 88, 'nombrePais' => 'Guadeloupe'],
      ['idPais' => 89, 'nombrePais' => 'Guam'],
      ['idPais' => 90, 'nombrePais' => 'Guatemala'],
      ['idPais' => 91, 'nombrePais' => 'Guernsey and Alderney'],
      ['idPais' => 92, 'nombrePais' => 'Guinea'],
      ['idPais' => 93, 'nombrePais' => 'Guinea-Bissau'],
      ['idPais' => 94, 'nombrePais' => 'Guyana'],
      ['idPais' => 95, 'nombrePais' => 'Haiti'],
      ['idPais' => 96, 'nombrePais' => 'Heard and McDonald Islands'],
      ['idPais' => 97, 'nombrePais' => 'Honduras'],
      ['idPais' => 98, 'nombrePais' => 'Hong Kong S.A.R.'],
      ['idPais' => 99, 'nombrePais' => 'Hungary'],
      ['idPais' => 100, 'nombrePais' => 'Iceland'],
      ['idPais' => 101, 'nombrePais' => 'India'],
      ['idPais' => 102, 'nombrePais' => 'Indonesia'],
      ['idPais' => 103, 'nombrePais' => 'Iran'],
      ['idPais' => 104, 'nombrePais' => 'Iraq'],
      ['idPais' => 105, 'nombrePais' => 'Ireland'],
      ['idPais' => 106, 'nombrePais' => 'Israel'],
      ['idPais' => 107, 'nombrePais' => 'Italy'],
      ['idPais' => 108, 'nombrePais' => 'Jamaica'],
      ['idPais' => 109, 'nombrePais' => 'Japan'],
      ['idPais' => 110, 'nombrePais' => 'Jersey'],
      ['idPais' => 111, 'nombrePais' => 'Jordan'],
      ['idPais' => 112, 'nombrePais' => 'Kazakhstan'],
      ['idPais' => 113, 'nombrePais' => 'Kenya'],
      ['idPais' => 114, 'nombrePais' => 'Kiribati'],
      ['idPais' => 115, 'nombrePais' => 'Korea North'],
      ['idPais' => 116, 'nombrePais' => 'Korea South'],
      ['idPais' => 117, 'nombrePais' => 'Kuwait'],
      ['idPais' => 118, 'nombrePais' => 'Kyrgyzstan'],
      ['idPais' => 119, 'nombrePais' => 'Laos'],
      ['idPais' => 120, 'nombrePais' => 'Latvia'],
      ['idPais' => 121, 'nombrePais' => 'Lebanon'],
      ['idPais' => 122, 'nombrePais' => 'Lesotho'],
      ['idPais' => 123, 'nombrePais' => 'Liberia'],
      ['idPais' => 124, 'nombrePais' => 'Libya'],
      ['idPais' => 125, 'nombrePais' => 'Liechtenstein'],
      ['idPais' => 126, 'nombrePais' => 'Lithuania'],
      ['idPais' => 127, 'nombrePais' => 'Luxembourg'],
      ['idPais' => 128, 'nombrePais' => 'Macau S.A.R.'],
      ['idPais' => 129, 'nombrePais' => 'Macedonia'],
      ['idPais' => 130, 'nombrePais' => 'Madagascar'],
      ['idPais' => 131, 'nombrePais' => 'Malawi'],
      ['idPais' => 132, 'nombrePais' => 'Malaysia'],
      ['idPais' => 133, 'nombrePais' => 'Maldives'],
      ['idPais' => 134, 'nombrePais' => 'Mali'],
      ['idPais' => 135, 'nombrePais' => 'Malta'],
      ['idPais' => 136, 'nombrePais' => 'Man (Isle of)'],
      ['idPais' => 137, 'nombrePais' => 'Marshall Islands'],
      ['idPais' => 138, 'nombrePais' => 'Martinique'],
      ['idPais' => 139, 'nombrePais' => 'Mauritania'],
      ['idPais' => 140, 'nombrePais' => 'Mauritius'],
      ['idPais' => 141, 'nombrePais' => 'Mayotte'],
      ['idPais' => 142, 'nombrePais' => 'Mexico'],
      ['idPais' => 143, 'nombrePais' => 'Micronesia'],
      ['idPais' => 144, 'nombrePais' => 'Moldova'],
      ['idPais' => 145, 'nombrePais' => 'Monaco'],
      ['idPais' => 146, 'nombrePais' => 'Mongolia'],
      ['idPais' => 147, 'nombrePais' => 'Montserrat'],
      ['idPais' => 148, 'nombrePais' => 'Morocco'],
      ['idPais' => 149, 'nombrePais' => 'Mozambique'],
      ['idPais' => 150, 'nombrePais' => 'Myanmar'],
      ['idPais' => 151, 'nombrePais' => 'Namibia'],
      ['idPais' => 152, 'nombrePais' => 'Nauru'],
      ['idPais' => 153, 'nombrePais' => 'Nepal'],
      ['idPais' => 154, 'nombrePais' => 'Netherlands Antilles'],
      ['idPais' => 155, 'nombrePais' => 'Netherlands The'],
      ['idPais' => 156, 'nombrePais' => 'New Caledonia'],
      ['idPais' => 157, 'nombrePais' => 'New Zealand'],
      ['idPais' => 158, 'nombrePais' => 'Nicaragua'],
      ['idPais' => 159, 'nombrePais' => 'Niger'],
      ['idPais' => 160, 'nombrePais' => 'Nigeria'],
      ['idPais' => 161, 'nombrePais' => 'Niue'],
      ['idPais' => 162, 'nombrePais' => 'Norfolk Island'],
      ['idPais' => 163, 'nombrePais' => 'Northern Mariana Islands'],
      ['idPais' => 164, 'nombrePais' => 'Norway'],
      ['idPais' => 165, 'nombrePais' => 'Oman'],
      ['idPais' => 166, 'nombrePais' => 'Pakistan'],
      ['idPais' => 167, 'nombrePais' => 'Palau'],
      ['idPais' => 168, 'nombrePais' => 'Palestinian Territory Occupied'],
      ['idPais' => 169, 'nombrePais' => 'Panama'],
      ['idPais' => 170, 'nombrePais' => 'Papua new Guinea'],
      ['idPais' => 171, 'nombrePais' => 'Paraguay'],
      ['idPais' => 172, 'nombrePais' => 'Peru'],
      ['idPais' => 173, 'nombrePais' => 'Philippines'],
      ['idPais' => 174, 'nombrePais' => 'Pitcairn Island'],
      ['idPais' => 175, 'nombrePais' => 'Poland'],
      ['idPais' => 176, 'nombrePais' => 'Portugal'],
      ['idPais' => 177, 'nombrePais' => 'Puerto Rico'],
      ['idPais' => 178, 'nombrePais' => 'Qatar'],
      ['idPais' => 179, 'nombrePais' => 'Reunion'],
      ['idPais' => 180, 'nombrePais' => 'Romania'],
      ['idPais' => 181, 'nombrePais' => 'Russia'],
      ['idPais' => 182, 'nombrePais' => 'Rwanda'],
      ['idPais' => 183, 'nombrePais' => 'Saint Helena'],
      ['idPais' => 184, 'nombrePais' => 'Saint Kitts And Nevis'],
      ['idPais' => 185, 'nombrePais' => 'Saint Lucia'],
      ['idPais' => 186, 'nombrePais' => 'Saint Pierre and Miquelon'],
      ['idPais' => 187, 'nombrePais' => 'Saint Vincent And The Grenadin'],
      ['idPais' => 188, 'nombrePais' => 'Samoa'],
      ['idPais' => 189, 'nombrePais' => 'San Marino'],
      ['idPais' => 190, 'nombrePais' => 'Sao Tome and Principe'],
      ['idPais' => 191, 'nombrePais' => 'Saudi Arabia'],
      ['idPais' => 192, 'nombrePais' => 'Senegal'],
      ['idPais' => 193, 'nombrePais' => 'Serbia'],
      ['idPais' => 194, 'nombrePais' => 'Seychelles'],
      ['idPais' => 195, 'nombrePais' => 'Sierra Leone'],
      ['idPais' => 196, 'nombrePais' => 'Singapore'],
      ['idPais' => 197, 'nombrePais' => 'Slovakia'],
      ['idPais' => 198, 'nombrePais' => 'Slovenia'],
      ['idPais' => 199, 'nombrePais' => 'Smaller Territories of the UK'],
      ['idPais' => 200, 'nombrePais' => 'Solomon Islands'],
      ['idPais' => 201, 'nombrePais' => 'Somalia'],
      ['idPais' => 202, 'nombrePais' => 'South Africa'],
      ['idPais' => 203, 'nombrePais' => 'South Georgia'],
      ['idPais' => 204, 'nombrePais' => 'South Sudan'],
      ['idPais' => 205, 'nombrePais' => 'Spain'],
      ['idPais' => 206, 'nombrePais' => 'Sri Lanka'],
      ['idPais' => 207, 'nombrePais' => 'Sudan'],
      ['idPais' => 208, 'nombrePais' => 'Suriname'],
      ['idPais' => 209, 'nombrePais' => 'Svalbard And Jan Mayen Islands'],
      ['idPais' => 210, 'nombrePais' => 'Swaziland'],
      ['idPais' => 211, 'nombrePais' => 'Sweden'],
      ['idPais' => 212, 'nombrePais' => 'Switzerland'],
      ['idPais' => 213, 'nombrePais' => 'Syria'],
      ['idPais' => 214, 'nombrePais' => 'Taiwan'],
      ['idPais' => 215, 'nombrePais' => 'Tajikistan'],
      ['idPais' => 216, 'nombrePais' => 'Tanzania'],
      ['idPais' => 217, 'nombrePais' => 'Thailand'],
      ['idPais' => 218, 'nombrePais' => 'Togo'],
      ['idPais' => 219, 'nombrePais' => 'Tokelau'],
      ['idPais' => 220, 'nombrePais' => 'Tonga'],
      ['idPais' => 221, 'nombrePais' => 'Trinidad And Tobago'],
      ['idPais' => 222, 'nombrePais' => 'Tunisia'],
      ['idPais' => 223, 'nombrePais' => 'Turkey'],
      ['idPais' => 224, 'nombrePais' => 'Turkmenistan'],
      ['idPais' => 225, 'nombrePais' => 'Turks And Caicos Islands'],
      ['idPais' => 226, 'nombrePais' => 'Tuvalu'],
      ['idPais' => 227, 'nombrePais' => 'Uganda'],
      ['idPais' => 228, 'nombrePais' => 'Ukraine'],
      ['idPais' => 229, 'nombrePais' => 'United Arab Emirates'],
      ['idPais' => 230, 'nombrePais' => 'United Kingdom'],
      ['idPais' => 231, 'nombrePais' => 'United States'],
      ['idPais' => 232, 'nombrePais' => 'United States Minor Outlying I'],
      ['idPais' => 233, 'nombrePais' => 'Uruguay'],
      ['idPais' => 234, 'nombrePais' => 'Uzbekistan'],
      ['idPais' => 235, 'nombrePais' => 'Vanuatu'],
      ['idPais' => 236, 'nombrePais' => 'Vatican City State (Holy See)'],
      ['idPais' => 237, 'nombrePais' => 'Venezuela'],
      ['idPais' => 238, 'nombrePais' => 'Vietnam'],
      ['idPais' => 239, 'nombrePais' => 'Virgin Islands (British)'],
      ['idPais' => 240, 'nombrePais' => 'Virgin Islands (US)'],
      ['idPais' => 241, 'nombrePais' => 'Wallis And Futuna Islands'],
      ['idPais' => 242, 'nombrePais' => 'Western Sahara'],
      ['idPais' => 243, 'nombrePais' => 'Yemen'],
      ['idPais' => 244, 'nombrePais' => 'Yugoslavia'],
      ['idPais' => 245, 'nombrePais' => 'Zambia'],
      ['idPais' => 246, 'nombrePais' => 'Zimbabwe']
    ];

    foreach ($countries as $country) {
      Pais::factory()->create($country);
    }
    // DB::unprepared(file_get_contents('database/migrations/pais.sql'));
  }
}
